"""Edit User model

Revision ID: 1b161aa6e8a4
Revises: ff29fdc3e7d6
Create Date: 2024-08-06 16:57:02.978546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b161aa6e8a4'
down_revision: Union[str, None] = 'ff29fdc3e7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_unique_constraint(None, 'User', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
