"""Edit comment model: add user_id column

Revision ID: 6583c24af0b6
Revises: 3780f1afdf77
Create Date: 2024-08-21 19:08:23.444402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6583c24af0b6'
down_revision: Union[str, None] = '3780f1afdf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CommentToComment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'CommentToComment', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('CommentToPost', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'CommentToPost', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CommentToPost', type_='foreignkey')
    op.drop_column('CommentToPost', 'user_id')
    op.drop_constraint(None, 'CommentToComment', type_='foreignkey')
    op.drop_column('CommentToComment', 'user_id')
    # ### end Alembic commands ###
