"""Edit Like model

Revision ID: 72f321b09b42
Revises: f54ec20810bf
Create Date: 2024-08-21 16:43:58.600217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f321b09b42'
down_revision: Union[str, None] = 'f54ec20810bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'LikePost', 'Post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'LikePost', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'LikePost', type_='foreignkey')
    op.drop_constraint(None, 'LikePost', type_='foreignkey')
    # ### end Alembic commands ###
