"""Add status archive and change to post

Revision ID: bed6a44a0379
Revises: 4820bd9d3de5
Create Date: 2024-08-10 13:08:57.643963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed6a44a0379'
down_revision: Union[str, None] = '4820bd9d3de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('Post', sa.Column('is_changed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Post', 'is_changed')
    op.drop_column('Post', 'is_archived')
    # ### end Alembic commands ###
