"""Add column created_at to Post

Revision ID: ff82d396e13c
Revises: bed6a44a0379
Create Date: 2024-08-10 14:55:24.339234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff82d396e13c'
down_revision: Union[str, None] = 'bed6a44a0379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Post', 'created_at')
    # ### end Alembic commands ###
