version: "3.9"
services:

  test_db:
    image: postgres:16.3-alpine
    container_name: postgres_container_test
    restart: always
    env_file:
      - .env


    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
      POSTGRES_DB: ${TEST_DB_NAME}


  test_runner:
    build: .
    container_name: test_runner_container
    depends_on:
      - test_db
    volumes:
      - .:/src
    command: >
      sh -c "pytest -v -s app/tests/"
    env_file:
      - .env
    environment:
      DB_HOST: ${TEST_DB_HOST}
      DB_PORT: ${TEST_DB_PORT}
      DB_USER: ${TEST_DB_USER}
      DB_PASS: ${TEST_DB_PASS}
      DB_NAME: ${TEST_DB_NAME}
