services:

  db:
    image: postgres:16.3-alpine
    container_name: postgres_container
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:6-alpine
    container_name: redis_container
    restart: always
    env_file:
      - .env

  cassandra:
    image: cassandra:3.11.17
    container_name: cassandra_container
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "Cluster"
      CASSANDRA_SEEDS: "cassandra"
      CASSANDRA_REPLICATION_FACTOR: "1"


  app_service:
    build: .
    container_name: app_service_container
    depends_on:
      - db
      - redis
      - cassandra

    links:
      - redis
      - cassandra

    ports:
      - 8000:8000

    volumes:
      - .:/src

    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    
    

    env_file:
      - .env



