services:

  db:
    image: postgres:16.3-alpine
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:6-alpine
    restart: always
    env_file:
      - .env

  app_service:
    build: .
    depends_on:
      - db
      - redis

    links:
      - redis

    ports:
      - 8000:8000

    volumes:
      - .:/src

    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    
    

    env_file:
      - .env



