services:

  test_db:
    image: postgres:16.3-alpine
    container_name: postgres_container_test
    restart: always
    env_file:
      - .env
    ports:
      - ${TEST_DB_PORT}:${TEST_DB_PORT}
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
      POSTGRES_DB: ${TEST_DB_NAME}


  test_app_service:
    build: .
    container_name: app_service_container_test
    depends_on:
      - test_db

    ports:
      - 8000:8000

    volumes:
      - .:/src

    command: >
      sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env

    environment:
      DB_HOST: ${TEST_DB_HOST}
      DB_PORT: ${TEST_DB_PORT}
      DB_USER: ${TEST_DB_USER}
      DB_PASS: ${TEST_DB_PASS}
      DB_NAME: ${TEST_DB_NAME}


  test_runner:
    build: .
    container_name: test_runner_container
    depends_on:
      - test_db
    volumes:
      - .:/src
    command: >
      sh -c "pytest app/tests/"
    env_file:
      - .env
    environment:
      DB_HOST: ${TEST_DB_HOST}
      DB_PORT: ${TEST_DB_PORT}
      DB_USER: ${TEST_DB_USER}
      DB_PASS: ${TEST_DB_PASS}
      DB_NAME: ${TEST_DB_NAME}
